must:
  uuid: 1001
  tags: [game]

modules: [play, account, web, agent]

log:
  stdout: ../logs/game.log
  stderr: ../logs/game.log

nmq:
  default:
    url: nats://127.0.0.1:4222

mgdb:
  default:
    host: 127.0.0.1
    port: 27017
    user:
    pass:
    name: game
