serverID: 1001

log:
  stdout: ../logs/duel.log
  stderr: ../logs/duel.log

nmq:
  default:
    url: nats://127.0.0.1:4222

mgdb:
  default:
    host: 127.0.0.1
    port: 27017
    user:
    pass:
    name: game
